### ISSUE TITLE
Add SiDi128?

### ISSUE THREAD

**Issue by eightbit0675** [gcopoix/makeSD_mist#1]
Not an issue but a feature request. Would you be able to add SiDi128 for SD card building to your script?

This script works very good, it would be great for SiDi128 owners too :)

**Comment by gcopoix** [comment]
Hi, I am currently adding the SiDi128 support (requires only a few changes in the scripts).
I will keep you informed, can you please test the installation for me (as I don't own a SiDi128)? I would push it to feature branch

**Comment by eightbit0675** [comment]
Thank you! Yes, I will gladly test it for you when it is ready!

**Comment by gcopoix** [comment]
Hi, added SiDi128 support - looks good for me (on file level), can you please test this on a SiDi128 device? Thank you in advance

**Comment by eightbit0675** [comment]
That's great! I will report back shortly!

**Comment by gcopoix** [comment]
genSD.sh -s sidi128
See [documentation->usage](https://github.com/gcopoix/makeSD_mist?tab=readme-ov-file#usage) or [documentation->usage](https://github.com/gcopoix/makeSD_mist?tab=readme-ov-file#examples)

**Comment by eightbit0675** [comment]
Got it. I am running the script now. One thing of note is that the link to https://stahlworks.com/dev/unzip.exe is dead so unzip tool does not download.

I used the wayback machine to get it through 

https://web.archive.org/web/20240507073856/https://stahlworks.com/dev/unzip.exe


I am running it now and will test when completed. Thanks for the help!

**Comment by gcopoix** [comment]
Thanks for the hint - got lost by changing links to https.
Can be downloaded as http://stahlworks.com/dev/unzip.exe
I will update it in the next days.

**Comment by eightbit0675** [comment]
It looks like the script worked fine as far as I can tell. I haven't tested everything of course, but I did bounce around checking cores and everything seems to check out fine.

One thing however is that on SiDi128 the "core.rbf" is named "sidi128.rbf" instead. So it needed to be renamed in order to boot.

**Comment by gcopoix** [comment]
Hi, first thanks for the feedback.
Are you sure about the menu core? According https://github.com/gcopoix/makeSD_mist/blob/main/Windows/genSD.ps1#L1198-L1200 (I think you used the Windows version) the menu core is always named `core.rbf`.
I've run a full test set last time, and I can't find any `sidi128.rbf` file anywhere.
Has this been some remaining file from a previous generation?

**Comment by eightbit0675** [comment]
I am positive. Menu core on the SiDi128 is not named core.rbf, but rather sidi128.rbf: https://github.com/ManuFerHi/SiDi-FPGA/tree/master/Cores/menu/

If named core.rbf, lights on the SiDi128 flash and the menu does not load.

**Comment by gcopoix** [comment]
"I did bounce around checking cores and everything **seems to check out fine**"
vs.
"If named core.rbf, lights on the SiDi128 flash and **the menu does not load**."

I am confused: What is (except the name of the menu core) the status ? Dies the menu boot, does it show the cores/folders, do the cores start/work?

**Comment by eightbit0675** [comment]
It's the menu that does not boot because it cannot be named "core.rbf". On original SiDi (and MiST) the menu core is named core.rbf. But on SiDi128, the menu core must be named "sidi128.rbf". 

After renaming it, it boots to the menu.

It is just the menu name that is the issue. Once the menu boots then you can load system cores just fine.

**Comment by eightbit0675** [comment]
I will also ask more SiDi128 owners to test the script in the Atari Forums and I will continue to test and report any more issues back to you. Thank you again!

**Comment by gcopoix** [comment]
Hi, thanks for that. I got in contact with Manuel Fernández Higueras (ManuFerHi), he added my repo link in his [Sidi128SD ReadMe](https://github.com/ManuFerHi/SiDi-FPGA/tree/master/SiDi128SD).
