### ISSUE TITLE
SD Cart MIST (Windows)

### ISSUE THREAD

**Issue by HtmlBosss** [gcopoix/makeSD_mist#3]
Hi, can you describe step by step how to make SD Cart MIST(Windows)?

**Comment by gcopoix** [comment]
1. like every other github repo, get the sources by either
   - clone this repo
     ``` git clone https://github.com/gcopoix/makeSD_mist.git```
     or
   - [download](https://github.com/gcopoix/makeSD_mist/archive/refs/heads/main.zip) as zip and unzip to your harddrive
3. depending on your OS:
   - with Windows:
      - cd into the makeSD_mist\Windows folder with the ComandLine or PowerShell (from start Menu)
      - for e.g. MiST:
      ```
      gensd -s mist -d F:
      ```
      (if F: is the destination folder you want to create the distribution to)
   - with Linux:
      - cd into the makeSD_mist/Linux folder with the Shell of your choice
      - for e.g. MiST:
      ```
      /gensd.sh -s mist -d /media/<your name>/SDCard
      ```
      (if /media/<your name>/SDCard is the destination folder you want to create the distribution to)
3. get some drink, this will take some hours.

PS: You had a look at the [documentation](https://github.com/gcopoix/makeSD_mist/blob/main/README.md) ?
Especially the sections
- [Preconditions](https://github.com/gcopoix/makeSD_mist/tree/main?tab=readme-ov-file#preconditions)
- [Usage](https://github.com/gcopoix/makeSD_mist/tree/main?tab=readme-ov-file#usage)
- [Examples](https://github.com/gcopoix/makeSD_mist/tree/main?tab=readme-ov-file#examples)

**Comment by HtmlBosss** [comment]
Thanks again for the help. It's my fault. I downloaded or got the wrong copy from Github. I spent the whole evening to generate my SD card. Today everything works fine. I downloaded a fresh copy of make_SD. I ran CMD as admin. With the line "genSD -s mist"
and everything started.

I had problems running the script with the command: "genSD -s sidi -d E:" because I have a 32Gb card. But I don't know if the size of the card has an impact on downloading the cores files. Everything took about 6 hours. SD directory 14Gb and repos directory about 12Gb.
I had a lot of errors, for example:
jotego/mra/_alternatives/_Yie Ar Kung-Fu/Yie Ar Kung-Fu (program code G).mra (Yie Ar Kung-Fu (program code G), jtyiear, yiear2.zip yiear.zip (0261)):
fetching 'https://archive.org/download/2020_01_06_fbn/roms/arcade.zip/arcade/yiear2.zip' ... failed.
fetching 'https://downloads.retrostic.com/roms/yiear2.zip' ... failed.
fetching 'https://archive.org/download/fbnarcade-fullnonmerged/arcade/yiear2.zip' ... done.
fetching 'https://archive.org/download/2020_01_06_fbn/roms/arcade.zip/arcade/yiear.zip' ... exists.
'Yie Ar Kung-Fu (program code G).mra': generating 'yiear2.rom' and 'Yie Ar Kung-Fu (program code G).arc'
Did you have that too?

**Comment by gcopoix** [comment]
Hi, good to hear it worked now.
As written in the [Known Issues](https://github.com/gcopoix/makeSD_mist?tab=readme-ov-file#known-issues) the downloading of the MAME roms is a bit tricky. In your example you can see, that the file `yiear2.zip` has been successfully downloaded from the 3rd server. So the ROMs have been created successfully.
This works mostly correct, but still some MAME roms aren't downloaded in the correct version (sometimes files in the archive are missing, sometimes the `mra` tool complains about wrong checksum.
It is a question about getting the MAME ROMs, and the script tries different download servers starting with the version mentioned in the .mra files.
So the behavior is as expected for now (until somebody has better download links for the MAME roms matching the version given in the .mra files).
